name: Continuous Integration
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the lint container
        run: DOCKER_BUILDKIT=1 docker-compose build lint
      # - name: Build the tests container
      #   run: DOCKER_BUILDKIT=1 docker-compose build tests
      - name: Check linting
        run: docker-compose run --rm lint
      # - name: Run tests
      #   run: docker-compose run --rm tests
